pso/homepage/urls.py
from django.urls import path
from . import views

app_name = 'homepage'

urlpatterns = [
    path('', views.home, name='home'),
    path('register/', views.UserFormView.as_view(), name='register'),
    path('login/', views.LoginFormView.as_view(), name='login'),
    path('logout/', views.logout, name='logout'),
    path('search/', views.SearchListView.as_view(), name='search'),
    path('autocomplete/', views.autocomplete, name='autocomplete'),
    path('faq/', views.faq, name='faq'),
    path('contactus/', views.contactus, name='contact_us'),
]

pso/pso/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('homepage.urls')),
    path('questions/', include('questionpage.urls')),
    path('profile/', include('userpage.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pso/questionpage/urls.py
from django.urls import path, re_path
from . import views

app_name = 'questionpage'

urlpatterns = [
    path('post/', views.PostQuestionView.as_view(), name='post_question'),
    re_path('^(?P<question_id>[0-9]+)/clear_notifications/$', views.clear_notification, name='clear_notification'),
    re_path('^(?P<question_id>[0-9]+)/$', views.detail, name='detail'),
    re_path('^(?P<question_id>[0-9]+)/answer/$', views.PostAnswerView.as_view(), name='answer'),
    re_path('^(?P<question_id>[0-9]+)/answer/(?P<ans_id>[0-9]+)/comment$', views.post_comment, name='comment'),
    re_path('^(?P<question_id>[0-9]+)/answer/(?P<ans_id>[0-9]+)/comment/(?P<comment_id>[0-9]+)/delete$', views.delete_comment, name='delete_comment'),
    re_path('^(?P<pk>[0-9]+)/edit/$', views.QuestionUpdate.as_view(), name='edit_question'),
    re_path('^(?P<pk>[0-9]+)/delete/$', views.QuestionDelete.as_view(), name='delete_question'),
    re_path('^(?P<question_id>[0-9]+)/answer/(?P<pk>[0-9]+)/edit$', views.AnswerUpdate.as_view(), name='edit_answer'),
    re_path('^(?P<question_id>[0-9]+)/answer/(?P<pk>[0-9]+)/delete$', views.AnswerDelete.as_view(), name='delete_answer'),
    re_path('^vote/(?P<text_type>[a-z]+)/(?P<text_id>[0-9]+)/change=(?P<score_change>[+-]1)/$', views.vote, name='vote'),
]

pso/userpage/urls.py
from django.urls import path, re_path
from . import views

app_name = 'userpage'

urlpatterns = [
    re_path('^(?P<username>[a-zA-Z0-9_]+)/$', views.profile, name='profile'),
    re_path('^(?P<username>[a-zA-Z0-9_]+)/graph$', views.graph, name='graph'),
    re_path('^(?P<username>[a-zA-Z0-9_]+)/password$', views.change_password, name='change_password'),
    re_path('^(?P<username>[a-zA-Z0-9_]+)/picture$', views.change_picture, name='change_picture'),
]

pso/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>{% block title %}{% endblock %}</title>
    <!-- jQuery !-->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.4/jquery-ui.min.js"></script>
    <link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.4/themes/smoothness/jquery-ui.css">

    <!-- Bootstrap !-->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    {% block extra_head %}{% endblock %}
</head>
<body>
    {% block content %}{% endblock %}
</body>
</html>

pso/templates/form_template.html
<!-- HTML code for display fields of a form -->

{% for field in form %}
    <div class="form-group">
        <label class="control-label col-sm-2">{{ field.label_tag}}</label>
        <div class="col-sm-10">{{ field }}</div>
    </div>
{% endfor %}

pso/templates/navbar.html
<!-- HTML code for top navigation bar common to all pages -->

<nav class="navbar navbar-default navbar-fixed-top">
    <div class="container-fluid">
        <div class="navbar-header">
            <!-- creates button to collapse options into drop down menu -->
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'homepage:home' %}">Pennstackoverflow</a>
        </div>

        <!-- items on top nav bar -->
        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav navbar-right ">
                <li>
                    <a href="{% url 'homepage:faq' %}">
                        <span class="glyphicon glyphicon-question-sign"></span>&nbsp;FAQ
                    </a>
                </li>
                <li>
                    <a href="{% url 'homepage:contact_us' %}">
                        <span class="glyphicon glyphicon-comment"></span>&nbsp;Contact Us
                    </a>
                </li>
                {% if not user.is_anonymous %}
                <li>
                    <a href="" data-toggle="modal" data-target="#postQuestionModal">
                        <span class="glyphicon glyphicon-pencil"></span>&nbsp;Post a Question
                    </a>
                </li>
                <li>
                    <a href="{% url 'homepage:logout' %}">
                        <span class="glyphicon glyphicon-log-out"></span>&nbsp;Logout
                    </a>
                </li>
                <li>
                    {% if not viewer == None %}
                    <a href="{% url 'userpage:profile' viewer.username %}">
                        <span class="glyphicon glyphicon-user"></span>&nbsp;My Profile
                    </a>
                    {% else %}


                    <a href="{% url 'userpage:profile' user.username %}">
                        <span class="glyphicon glyphicon-user"></span>&nbsp;My Profile
                    </a>
                    {% endif%}
                </li>
                {% else %}
                <li>
                    <!-- can add icon by inserting the line between anchor tags -->
                    <a href="{% url 'homepage:login' %}">
                        <span class="glyphicon glyphicon-log-in"></span>&nbsp;Login
                    </a>
                </li>
                <li>
                    <a href="{% url 'homepage:register' %}">
                        <span class="glyphicon glyphicon-plus"></span>&nbsp;Register
                    </a>
                </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

<!-- modal for submitting a new question -->
<div class="modal fade" id="postQuestionModal" role="dialog">
    <div class="modal-dialog">
        <!-- Modal content-->
        <div style="padding-left:10px;padding-right:10px;" id="postQuestionModalContent" class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Post a Question</h4>
            </div>
            <div class="modal-body">
                <form class="form-horizontal" role="form" action="{% url 'questionpage:post_question' %}" method="post">
                    {% csrf_token %}
                    <div class="form-group">
                        <label>Title</label>
                        <input name="title" type="text" class="form-control" placeholder="Enter title of question" required="required">
                        <div class="help-block with-errors"></div>
                    </div>
                    <div class="form-group">
                        <textarea name="body" class="form-control" placeholder="My question..." rows="4" required="required"></textarea>
                        <div class="help-block with-errors"></div>
                    </div>
                    <div class="form-group">
                        <label>Tags</label>
                        <input name="tags" type="text" class="form-control" placeholder="My tags..." required="required">
                        <div class="help-block with-errors"></div>
                    </div>
                    <div class="form-group">
                        <button type="submit" class="btn btn-success">Submit</button>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

pso/templates/pagination.html
<!-- HTML code for pagination -->

<div class="row" id="pagination-row">
    <div class="panel panel-default">
            <div class="pagination">
                <span class="step-links">
                    {% if all_questions.has_previous %}
                        <a href="?page={{ all_questions.previous_page_number }}">
                            <span class="glyphicon glyphicon-chevron-left"></span>
                        </a>
                    {% endif %}

                    <span class="current">
                        {{ all_questions.number }} of {{ all_questions.paginator.num_pages }}
                    </span>

                    {% if all_questions.has_next %}
                        <a href="?page={{ all_questions.paginator.num_pages }}">
                            <span class="glyphicon glyphicon-chevron-right"></span>
                        </a>
                    {% endif %}
                </span>
            </div>
    </div>
</div>