pso/homepage/urls.py
from django.urls import path
from . import views

app_name = 'homepage'

urlpatterns = [
    path('', views.home, name='home'),
    path('register/', views.UserFormView.as_view(), name='register'),
    path('login/', views.LoginFormView.as_view(), name='login'),
    path('logout/', views.logout, name='logout'),
    path('search/', views.SearchListView.as_view(), name='search'),
    path('autocomplete/', views.autocomplete, name='autocomplete'),
    path('faq/', views.faq, name='faq'),
    path('contactus/', views.contactus, name='contact_us'),
]

pso/pso/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('homepage.urls')),
    path('questions/', include('questionpage.urls')),
    path('profile/', include('userpage.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pso/questionpage/urls.py
from django.urls import path, re_path
from . import views

app_name = 'questionpage'

urlpatterns = [
    path('post/', views.PostQuestionView.as_view(), name='post_question'),
    re_path('^(?P<question_id>[0-9]+)/clear_notifications/$', views.clear_notification, name='clear_notification'),
    re_path('^(?P<question_id>[0-9]+)/$', views.detail, name='detail'),
    re_path('^(?P<question_id>[0-9]+)/answer/$', views.PostAnswerView.as_view(), name='answer'),
    re_path('^(?P<question_id>[0-9]+)/answer/(?P<ans_id>[0-9]+)/comment$', views.post_comment, name='comment'),
    re_path('^(?P<question_id>[0-9]+)/answer/(?P<ans_id>[0-9]+)/comment/(?P<comment_id>[0-9]+)/delete$', views.delete_comment, name='delete_comment'),
    re_path('^(?P<pk>[0-9]+)/edit/$', views.QuestionUpdate.as_view(), name='edit_question'),
    re_path('^(?P<pk>[0-9]+)/delete/$', views.QuestionDelete.as_view(), name='delete_question'),
    re_path('^(?P<question_id>[0-9]+)/answer/(?P<pk>[0-9]+)/edit$', views.AnswerUpdate.as_view(), name='edit_answer'),
    re_path('^(?P<question_id>[0-9]+)/answer/(?P<pk>[0-9]+)/delete$', views.AnswerDelete.as_view(), name='delete_answer'),
    re_path('^vote/(?P<text_type>[a-z]+)/(?P<text_id>[0-9]+)/change=(?P<score_change>[+-]1)/$', views.vote, name='vote'),
]

pso/questionpage/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User

class Question(models.Model):
    title = models.CharField(max_length=200, blank=False)
    body = models.TextField(blank=False)
    tags = models.CharField(max_length=200, blank=True)
    date_posted = models.DateTimeField(default=timezone.now)
    author = models.ForeignKey(User, on_delete=models.CASCADE, null=False)
    score = models.IntegerField(default=0)

    def __str__(self):
        return self.title

    def tags_as_list(self):
        return self.tags.split(',')

class Answer(models.Model):
    list_display=('id',)
    author = models.ForeignKey(User, on_delete=models.CASCADE, null=False)
    date_posted = models.DateTimeField(default=timezone.now)
    body = models.TextField(blank=False)
    question_answered = models.ForeignKey(Question, on_delete=models.CASCADE, null=False)
    score = models.IntegerField(default=0)

    def __unicode__(self):
        return str(self.pk)

class Comment(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, null=False)
    date_posted = models.DateTimeField(default=timezone.now, blank=False)
    body = models.TextField()
    answer_commented = models.ForeignKey(Answer, related_name = 'comments', on_delete=models.CASCADE, default=None)
    score = models.IntegerField(default=0)

    def __str__(self):
        return (str(self.author) + "'s' Comment")

## TODO: Return to this idea -- make sure users can't upvote or downvote multiple times

class Vote(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=False) ##TODO: Check this -- does this make sense?
    text_id = models.PositiveIntegerField()
    is_upvoted = models.IntegerField()
    text_type = models.TextField()

    def check_if_upvoted(self):
        return self.is_upvoted

    def __str__(self):
        return (str(self.user) + "'s' Vote")


class Notification(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=False)
    question = models.ForeignKey(Question, on_delete=models.CASCADE, null=False)
    answer = models.ForeignKey(Answer, on_delete=models.CASCADE, null=False)

    def __str__(self):
        strng = "Someone answered your question '{}...'"
        return (strng.format(self.question.title[:40]))

pso/questionpage/forms.py
from django.contrib.auth.models import User
from django import forms
from questionpage.models import Question, Answer


class AnswerForm(forms.ModelForm):
    body = forms.CharField(widget=forms.Textarea)

    class Meta:
        model = Answer
        fields = ['body']

class QuestionForm(forms.ModelForm):
    title = forms.CharField(max_length=200)
    body = forms.CharField(widget=forms.Textarea)
    tags = forms.CharField(max_length=200)

    class Meta:
        model = Question
        fields = ['title', 'body', 'tags']

pso/questionpage/views.py
from django.shortcuts import render, get_object_or_404, redirect
from questionpage.models import Question, Answer, Comment, Vote, Notification
from django.views.generic import View
from django.contrib.auth.mixins import LoginRequiredMixin
from .forms import AnswerForm, QuestionForm
from django.template.defaulttags import register
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth import authenticate, login, logout as django_logout
from django.views.generic.edit import UpdateView, DeleteView
from django.urls import reverse_lazy, reverse
import bleach, re
import sys


def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    answers = list(Answer.objects.filter(question_answered__id=question_id).order_by('-score'))
    context = {'question': question, 'user': request.user, 'answers': answers}
    return render(request, 'questionpage/index.html', context)


def clear_notification(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    notifications = Notification.objects.filter(question=question).delete()
    return detail(request, question_id)


def vote(request, text_id, score_change, text_type):
    score_change = int(score_change)

    if (text_type == 'question'):
        return_id = text_id
        voted = get_object_or_404(Question, pk=text_id)
    elif (text_type == 'answer'):
        return_id = get_object_or_404(Answer, pk=text_id).question_answered.id
        voted = get_object_or_404(Answer, pk=text_id)
    else:
        return_id = get_object_or_404(Comment, pk=text_id).answer_commented.question_answered.id
        voted = get_object_or_404(Comment, pk=text_id)

    if request.user.is_authenticated:
        if vote_already_exists(user=request.user, text_id=text_id, text_type=text_type, is_upvoted=score_change):
            score_change = 0
        elif vote_is_being_switched(user=request.user, text_id=text_id, text_type=text_type, is_upvoted=score_change):
            Vote.objects.get(user=request.user, text_id=text_id, text_type=text_type, is_upvoted=(score_change*-1)).delete()
            new_vote = Vote(user=request.user, text_id=text_id, text_type=text_type, is_upvoted=score_change)
            new_vote.save()
            score_change *= 2 # need to increment by + or - 2 to overcome original vote
        else:
            new_vote = Vote(user=request.user, text_id=text_id, text_type=text_type, is_upvoted=score_change)
            new_vote.save()
    else:
        score_change = 0

    voted.score += score_change
    voted.save()
    return detail(request, return_id)


def vote_already_exists(user, text_id, text_type, is_upvoted):
    if Vote.objects.filter(user=user, text_id=text_id, text_type=text_type, is_upvoted=is_upvoted).count() > 0:
        return True
    else:
        return False


def vote_is_being_switched(user, text_id, text_type, is_upvoted):
    if Vote.objects.filter(user=user, text_id=text_id, text_type=text_type).count() > 0:
        return True
    else:
        return False


def post_comment(request, question_id, ans_id):
    answer = get_object_or_404(Answer, pk=ans_id)
    Comment(author=request.user, body=request.POST.get("text"), answer_commented=answer).save()
    return HttpResponseRedirect('../..')


def delete_comment(request, question_id, ans_id, comment_id):
    return_id = get_object_or_404(Comment, pk=comment_id).answer_commented.question_answered.id
    Comment.objects.filter(id=comment_id).delete()
    to_link = '/questions/%s/' % (question_id)
    return HttpResponseRedirect(redirect_to=to_link)


class AnswerUpdate(UpdateView):
    model = Answer
    fields = ['body']
    template_name = 'questionpage/answer_question_form.html'
    success_url = '../..'


class AnswerDelete(DeleteView):
    model = Answer
    fields = ['body']
    template_name = 'questionpage/delete_form.html'
    success_url = '../..'


class QuestionUpdate(UpdateView):
    model = Question
    fields = ['title', 'body', 'tags']
    template_name = 'questionpage/edit_question_form.html'
    success_url = '..'


class QuestionDelete(DeleteView):
    model = Question
    fields = ['title', 'body', 'tags']
    template_name = 'questionpage/delete_form.html'
    def get_success_url(self):
        return reverse_lazy('homepage:home')


def add_question_hyperlinks(text):
    new_text = text
    matches = re.findall(r'(@[0-9]+)', new_text)
    for at_q in matches:
        q_num = at_q[1:]
        link = '<a href="http://127.0.0.1:8000/questions/' + q_num + '/">' + at_q + "</a>"
        new_text = re.sub(at_q, link, new_text)
    return new_text


class PostQuestionView(LoginRequiredMixin, View):
    form_class = QuestionForm
    template_name = 'questionpage/post_question_form.html'
    login_url = '/login/'
    redirect_field_name = ''

    def get(self, request):
        form = self.form_class(None)
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        author = request.user
        title = request.POST['title']
        title = bleach.clean(title, tags = ['b', 'a'],)
        body = request.POST['body']
        body = add_question_hyperlinks(body)
        body = bleach.clean(body, tags = ['b', 'a'],)
        tags = self.clean_tags(request.POST['tags'])
        Question(author=author, title=title, body=body, tags=tags).save()
        print(request.path)
        return HttpResponseRedirect('/')

    def clean_tags(self, tags):
        tag_lst = [tag.strip() for tag in tags.split(",")]
        tag_lst = [tag for tag in tag_lst if tag and tag.isalnum()]
        tags = ",".join(tag_lst)
        return tags


class PostAnswerView(LoginRequiredMixin, View):
    form_class = AnswerForm
    template_name = 'questionpage/answer_question_form.html'
    login_url = '/login/'

    def get(self, request, question_id):
        form = self.form_class(None)
        return render(request, self.template_name, {'form': form})

    def post(self, request, question_id):
        body = request.POST['body']
        body = add_question_hyperlinks(body)
        body = bleach.clean(body, tags=['b', 'a'], )
        question = get_object_or_404(Question, pk=question_id)
        answer = Answer(author=request.user, body=body, question_answered=question)
        answer.save()
        create_notification(question.author, question, answer)
        return HttpResponseRedirect('..')


def create_notification(user, question, answer):
    if not Notification.objects.filter(question=question).exists():
        notification = Notification(user=user, question=question, answer=answer)
        notification.save()

pso/questionpage/templates/questionpage/answer_question_form.html
<!-- HTML for editing an answer page -->

{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}Edit an Answer - PSO{% endblock %}

{% block extra_head %}
<link href="{% static 'css/navbar.css' %}" rel="stylesheet" type="text/css"/>
<style>
    body {
        margin-top: 60px;
    }
</style>
{% endblock %}

{% block content %}
{% include 'navbar.html' %}
{% autoescape off %}

<div class="row">
    <div style="margin-left:50px;" class="col-md-4">
        <h2> Edit an Answer </h2>
        <form class="form-horizontal" role="form" action="" method="post">
            {% csrf_token %}
            {% include 'form_template.html' %}
            <div class="form-group">
                <div class="col-sm-offset-2 col-sm-10">
                    <button type="submit" class="btn btn-success">Submit</button>
                    <a href="/" class="btn btn-default">Back to the Homepage</a>
                </div>
            </div>
        </form>
    </div>
</div>

{% endautoescape %}

{% endblock %}

pso/questionpage/templates/questionpage/delete_form.html
<!-- HTML code for displaying delete page -->

{% extends 'base.html' %}
{% load staticfiles %}

{% block title %}Delete Question - PSO{% endblock %}

{% block extra_head %}
<link href="{% static 'css/navbar.css' %}" rel="stylesheet" type="text/css">
<style>
    body {
        padding-top: 60px;
    }
    .delete-alert {
        margin-left: 50px;
        margin-top: 50px;
    }
</style>
{% endblock %}

{% block content %}
{% include 'navbar.html' %}

<div class="row">
    <div class="col-md-4 delete-alert">
        <center>
            <div class="alert alert-warning" role="alert">
                <h4 class="alert-heading">You're about to delete something!</h4>
                <hr>
                <form class="form-horizontal" role="form" action="" method="post">
                    {% csrf_token %}
                    {% include 'form_template.html' %}
                    <div class="form-group">
                        <p> Are you sure you want to delete this item? </p>
                        <button type="submit" class="btn btn-success">Delete</button>
                    </div>
                </form>
            </div>
        </center>
    </div>
</div>

{% endblock %}

pso/questionpage/templates/questionpage/edit_question_form.html
<!-- HTML code for editing a question -->

{% extends 'base.html' %}
{% load static %}

{% block title %}Edit Question - PSO{% endblock %}

{% block extra_head %}
<link href="{% static 'css/navbar.css' %}" rel="stylesheet" type="text/css"/>
<link href="{% static 'questionpage/css/post_question.css' %}" rel="stylesheet" type="text/css"/>
{% endblock %}


{% block content %}

{% autoescape off %}

{% include 'navbar.html' %}
<div class="row">
    <div style="margin-left:50px;" class="col-md-4">
        <h2> Edit a Question </h2>
        <form class="form-horizontal" role="form" action="" method="post">
            {% csrf_token %}
            {% include 'form_template.html' %}
            <div class="form-group">
                <div class="col-sm-offset-2 col-sm-10">
                    <button type="submit" class="btn btn-success">Submit</button>
                    <a href="/" class="btn btn-default">Back to the Homepage</a>
                </div>
            </div>
        </form>
    </div>
</div>

{% endautoescape %}

{% endblock %}

pso/questionpage/templates/questionpage/index.html
<!-- HTML code for displaying a particular question -->

{% extends 'base.html' %}
{% load staticfiles %}

{% block title %}{{ question.title }}{% endblock %}


{% block extra_head %}
<link href="{% static 'css/navbar.css' %}" rel="stylesheet" type="text/css">
<link href="{% static 'questionpage/css/view_question.css' %}" rel="stylesheet" type="text/css">
{% endblock %}


{% block content %}

<!-- top navigation bar -->
{% include 'navbar.html' %}

<!-- question title -->
<div class="row question_title">
    <h3 class="display-1">{{ question.title }}</h3>
    <hr class="title_underline">
</div>

<!-- question content -->
<div class="row">
    <!-- vote bar for question -->
    <div class="col-md-2 vote_bar">
        <h3>
            <a href="{% url 'questionpage:vote' text_id=question.id score_change="+1" text_type='question' %}" class="glyphicon glyphicon-triangle-top"></a>
            <br />&nbsp;{{question.score}}<br />
            <a href="{% url 'questionpage:vote' text_id=question.id score_change="-1" text_type="question" %}" class="glyphicon glyphicon-triangle-bottom"></a>
        </h3>

        {% if user.is_authenticated and user == question.author %}
            <a href="{% url 'questionpage:edit_question' question.id %}" class="glyphicon glyphicon-pencil"></a>
            <a href="{% url 'questionpage:delete_question' question.id %}" class="glyphicon glyphicon-trash"></a>
        {% endif %}
    </div>

    <!-- question body -->
    <div class="col-md-6">
        <div class="card card-body">
            <br>
            <h4>{% autoescape off %}{{ question.body }}{% endautoescape %}</h4>
            <br>
            <h4>Tags:
                {% for t in question.tags_as_list %}
                    <a href="/search?query=[{{ t }}]">#{{ t }}</a>
                {% endfor %}
            </h4>
        </div>
    </div>
    <!-- question info panel on right -->
    <div class="col-md-4">
        <br>
        <h4>asked on: {{ question.date_posted }}</h4>
        <h4>asked by: {{ question.author }}</h4><br>
    </div>
</div>

<!-- display answers -->
<div class="row answer_content">
    <h3> {{ answers|length }} Answers </h3>
    <hr class="answer_underline">

    {% for ans in answers %}
    <div class="row">
        <!-- answer vote bar -->
        <div class="col-md-1">
            <h3>
                <a href="{% url 'questionpage:vote' text_id=ans.id score_change="+1" text_type="answer" %}" class="glyphicon glyphicon-triangle-top"></a>
                <br />&nbsp;{{ans.score}}<br />
                <a href="{% url 'questionpage:vote' text_id=ans.id score_change="-1" text_type="answer" %}" class="glyphicon glyphicon-triangle-bottom"></a>
            </h3>
            {% if user.is_authenticated and user == ans.author %}
                <a href="{% url 'questionpage:edit_answer' question.id ans.id %}" class="glyphicon glyphicon-pencil"></a>
                <a href="{% url 'questionpage:delete_answer' question.id ans.id %}" class="glyphicon glyphicon-trash"></a>
            {% endif %}
        </div>
        <!-- answer body -->
        <div style="padding-left:50px;" class="col-md-6">
            <div class="card card-body">
                <br>
                <h4>{% autoescape off %}{{ ans.body }}{% endautoescape %}</h4>
            </div>
        </div>
        <!-- answer info panel on right -->
        <div class="col-md-4">
            <br>
            <h4>Answered on: {{ ans.date_posted }}</h4>
            <h4>Answered by: {{ ans.author }}</h4><br>
        </div>
    </div>
    <!-- comments for this particular answer -->
    <div class="row">
        <div class="col-md-10 pull-right comments">
            <hr class="comment_underline">
            {% for comment in ans.comments.all %}
                <a href="{% url 'questionpage:vote' text_id=comment.id score_change="+1" text_type="comment" %}" class="glyphicon glyphicon-thumbs-up"></a>
                {{ comment.score }}
                <a href="{% url 'questionpage:vote' text_id=comment.id score_change="-1" text_type="comment" %}" class="glyphicon glyphicon-thumbs-down"></a>
                {% if user.is_authenticated and user == comment.author %}
                    <a href="{% url 'questionpage:delete_comment' question.id ans.id comment.id %}" class="glyphicon glyphicon-trash"></a>
                {% endif %}
                &nbsp;&nbsp;&nbsp; {{ comment.body }}
                <b>- Posted by {{ comment.author }} on {{ comment.date_posted }}</b>
                <hr class="comment_underline">
            {% endfor %}

            <!-- form to submit comment -->
            {% include 'questionpage/submitcommentbox.html' %}
        </div>
    </div>
    <hr class="answer_underline">
    {% endfor %}
    <!-- form to submit answer -->
    {% if user.is_authenticated %}
        {% include 'questionpage/submitanswerbox.html' %}
    {% endif %}
</div>
{% endblock %}

pso/questionpage/templates/questionpage/submitanswerbox.html
<!-- HTMl code for submit button at bottom of question page -->
<div>
    <form class="form-horizontal" role="form" action="{% url 'questionpage:answer' question.id %}" method="post">
        {% csrf_token %}
        <div id="answer-form" class="form-group">
            <h4>Submit an Answer</h4>
            <textarea name="body" class="form-control" placeholder="My answer..." rows="4" required="required" data-error="No answer detected"></textarea>
            <div class="help-block with-errors"></div>
            <button type="submit" class="btn btn-success">Submit</button>
        </div>
     </form>
</div>

pso/questionpage/templates/questionpage/submitcommentbox.html
<!-- HTMl code for comment modal -->

{% if user.is_authenticated %}
<h4><a href="" data-toggle="modal" data-target="#commentModalLoggedIn">&nbsp;add a comment</a></h4>
{% else %}
<h4><a href="" data-toggle="modal" data-target="#commentModalLoggedOut">&nbsp;add a comment</a></h4>
{% endif %}

<!-- Modal that holds form to submit a comment, appears when user is logged in -->
<div class="modal fade" id="commentModalLoggedIn" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <!-- title of pop up -->
            <div class="modal-header">
                <h4 class="modal-title">Add a Comment</h4>
            </div>
            <!-- body of pop up, contains submit form -->
            <div class="modal-body">
                <form class="form-horizontal" role="form" action="{% url 'questionpage:comment' question.id ans.id %}" method="post">
                    {% csrf_token %}
                    <div id="comment-pop-up" class="form-group">
                        <textarea name="text" class="form-control" placeholder="My comment..." rows="4" required="required" data-error="Please insert a comment"></textarea>
                        <div class="help-block with-errors"></div>
                        <button type="submit" class="btn btn-success">Submit</button>
                    </div>
                 </form>
            </div>
            <!-- close button -->
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
      </div>
    </div>
</div>

<div class="modal fade" id="commentModalLoggedOut" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <!-- title of pop up -->
            <div class="modal-header">
                <h4 class="modal-title">Log into your account before you can comment!</h4>
            </div>
            <!-- body of pop up, contains login form -->
            <div class="modal-body">
                <form action="{% url 'homepage:login' %}" method="post">
                    {% csrf_token %}
                    <div class="row">
                        <!-- username box -->
                        <div class="form-group">
                            <div class="col-md-8">
                                <label>Username</label>
                                <input type="username" name="username" class="form-control" placeholder="Enter username">
                            </div>
                        </div>
                    </div><br>
                    <div class="row">
                        <!-- password box -->
                        <div class="col-md-8">
                            <div class="form-group">
                                <label>Password</label>
                                <input type="password" name="password" class="form-control" placeholder="Password">
                            </div>
                        </div>
                    </div>
                    <button type="submit" class="btn btn-default">Login</button>
                </form>
            </div>
            <!-- close button -->
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
      </div>
    </div>
</div>