pso/pso/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('homepage.urls')),
    path('questions/', include('questionpage.urls')),
    path('profile/', include('userpage.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pso/userpage/urls.py
from django.urls import path, re_path
from . import views

app_name = 'userpage'

urlpatterns = [
    re_path('^(?P<username>[a-zA-Z0-9_]+)/$', views.profile, name='profile'),
    re_path('^(?P<username>[a-zA-Z0-9_]+)/graph$', views.graph, name='graph'),
    re_path('^(?P<username>[a-zA-Z0-9_]+)/password$', views.change_password, name='change_password'),
    re_path('^(?P<username>[a-zA-Z0-9_]+)/picture$', views.change_picture, name='change_picture'),
]

pso/userpage/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver

class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE,
            primary_key=True, null=False, related_name='profile')
    picture = models.ImageField(upload_to='profile_pics', 
            default='profile_pics/default.png')

    def __str__(self):
        return "{}'s profile".format(self.user)

@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created: UserProfile.objects.create(user=instance)

@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()

pso/userpage/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.models import User
from django.contrib import messages
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.forms import PasswordChangeForm
from questionpage.models import Question, Answer, Comment
from django.http import HttpResponse
from .fusioncharts import FusionCharts


def change_password(request, username):
    if (request.user.username == username):
        if request.method == 'POST':
            form = PasswordChangeForm(request.user, request.POST)
            if form.is_valid():
                user = form.save()
                update_session_auth_hash(request, user)  # Important!
                messages.success(request, 'Your password was successfully updated!')
                return profile(request, username)
            else:
                messages.error(request, 'Please correct the error below.')
        else:
            form = PasswordChangeForm(request.user)
        return render(request, 'userpage/change_password.html', {
            'form': form
        })
    else:
        return redirect('/')


def profile(request, username):
    user = get_object_or_404(User, username=username)
    questions = Question.objects.filter(author=user).order_by('date_posted')
    answers = Answer.objects.filter(author=user).order_by('date_posted')
    context = dict(user=user, questions=questions, answers=answers, viewer=request.user)
    return render(request, 'userpage/profile.html', context)


def graph(request, username):
    user = get_object_or_404(User, username=username)
    questions = Question.objects.filter(author=user).order_by('date_posted')
    answers = Answer.objects.filter(author=user).order_by('date_posted')
    comments = Comment.objects.filter(author=user).order_by('date_posted')

    column2d = FusionCharts("column2d", "ex1" , "600", "400", "chart-1", "json",
          # The data is passed as a string in the `dataSource` as parameter.
      """{
            "chart":{
              "caption":"%s\'s Contributions",
              "subCaption":"Contributions to Penn Stack Overflow",
              "numberPrefix":"",
              "theme":"ocean"
            },
            "data":[
              {"label":"Questions", "value":"%s"},
              {"label":"Answers", "value":"%s"},
              {"label":"Comments", "value":"%s"},
            ]
        }""" % (username, len(questions), len(answers), len(comments)))
    return render(request, 'userpage/graph.html', {'output' : column2d.render()})

def change_picture(request, username):
    if (request.user.username == username):
        if request.method == 'POST':
            user = User.objects.get(username=username)
            img = request.FILES["mypicture"]
            user.profile.picture = img
            user.profile.save()
            return redirect('.')
        else:
            return render(request, 'userpage/change_picture.html')
    else:
        return redirect('/')

pso/userpage/templates/userpage/change_password.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block title %}Change Password - PSO{% endblock %}

{% block extra_head %}
<link href="{% static 'css/navbar.css' %}" rel="stylesheet" type="text/css"/>
<style>
    body {
        margin-top: 70px;
    }

    #change-password {
        margin-left: 20px;
    }
</style>
{% endblock %}

{% block content %}

{% include 'navbar.html' %}

<div class="row">
    <div id="change-password" class="col-md-2">
        <form method="post">
          {% csrf_token %}
          {{ form }}
          <button type="submit">Save changes</button>
        </form>
    </div>
</div>

{% endblock %}

pso/userpage/templates/userpage/change_picture.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block title %} User Profile {% endblock %}

{% block extra_head %}
<link href="{% static 'css/navbar.css' %}" rel="stylesheet" type="text/css"/>
<link href="{% static 'userpage/css/profile.css' %}" rel="stylesheet" type="text/css">
{% endblock %}

{% block content %}

<!-- top navigation bar -->
{% include 'navbar.html' %}

    <form method="post" action="" enctype="multipart/form-data">
        {% csrf_token %}
        <input type="file" name="mypicture"/>
        <input type="submit" name="submit" value="Upload" />
    </form>

{% endblock %}

pso/userpage/templates/userpage/graph.html
{% extends 'base.html' %}
{% block content %}

   <head>
    {% load static %}
   <script type="text/javascript" src="{% static 'userpage/js/fusioncharts.js' %}"></script>
   <script type="text/javascript" src="{% static 'userpage/js/themes/fusioncharts.theme.fint.js' %}"></script>
</head>
<body>
    <div id="chart-1">{{ output|safe }}</div>
</body>
    <a href="/" class="btn btn-default">Back to the Homepage</a>
    <a href="." class="btn btn-default">Back to Profile</a>


{% endblock %}

pso/userpage/templates/userpage/profile.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block title %}User Profile{% endblock %}

{% block extra_head %}
<link href="{% static 'css/navbar.css' %}" rel="stylesheet" type="text/css"/>
<link href="{% static 'userpage/css/profile.css' %}" rel="stylesheet" type="text/css">
{% endblock %}

{% block content %}

<!-- top navigation bar -->
{% include 'navbar.html' %}
<div class="row">
    <div class="col-md-6 profile-box">
        <h2>Welcome to {{ user.profile }}! </h2>
        <hr class="section_header"><br>
        <div id="profile-image">
            <img src="{{ user.profile.picture.url }}" class="img-thumbnail" width="250">
        </div>
    </div>
    <div class="col-md-6">
        <h2>Account Settings</h2>
        <hr class="section_header">
        <h4><a href="{% url 'userpage:graph' user %}">View account statistics
            <span class="glyphicon glyphicon-stats"></span>
        </a></h4>
        {% if viewer.is_authenticated and user == viewer %}
        <h4><a href="{% url 'userpage:change_password' user %}">Change password
            <span class="glyphicon glyphicon-lock"></span>
        </a></h4>
        <h4><a href="{% url 'userpage:change_picture' user%}">Change picture
            <span class="glyphicon glyphicon-picture"></span>
            </a></h4>
        {% endif %}
    </div>


</div>
<br><br>
<div class="row">
    <div class="col-md-6 question-stat-box">
        <h2>{{ user }}'s Questions</h2>
        <hr class="section_header">
        <div id="question-list">
            <ul class="list-group list-group-flush">
                {% if not questions %}
                    <p>You have not written any questions!</p>
                {% else %}
                {% for question in questions %}
                    <li class="list-group-item">
                        <a href="/questions/{{ question.id }}/">
                            {{ question.title }}
                        </a>
                        - {{ question.date_posted }}
                    </li>
                {% endfor %}
                {% endif %}
            </ul>
        </div>
    </div>
    <div class="col-md-6">
        <h2>{{ user }}'s Answers</h2>
        <hr class="section_header">
        <div id="answer-list">
            <ul class="list-group list-group-flush">
                {% if not answers %}
                    <p>You have not written any answers!</p>
                {% else %}
                {% for answer in answers %}
                <li class="list-group-item">
                    <b>{{ answer.question_answered.title }}: </b>
                    <a href="/questions/{{ answer.question_answered.id }}/">
                        {{ answer.body | truncatewords:10 }}
                    </a>
                    - {{ answer.date_posted }}
                </li>
                {% endfor %}
                {% endif %}
            </ul>
        </div>
    </div>
</div>
{% endblock %}