pso/homepage/urls.py
from django.urls import path
from . import views

app_name = 'homepage'

urlpatterns = [
    path('', views.home, name='home'),
    path('register/', views.UserFormView.as_view(), name='register'),
    path('login/', views.LoginFormView.as_view(), name='login'),
    path('logout/', views.logout, name='logout'),
    path('search/', views.SearchListView.as_view(), name='search'),
    path('autocomplete/', views.autocomplete, name='autocomplete'),
    path('faq/', views.faq, name='faq'),
    path('contactus/', views.contactus, name='contact_us'),
]

pso/pso/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('homepage.urls')),
    path('questions/', include('questionpage.urls')),
    path('profile/', include('userpage.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pso/questionpage/urls.py
from django.urls import path, re_path
from . import views

app_name = 'questionpage'

urlpatterns = [
    path('post/', views.PostQuestionView.as_view(), name='post_question'),
    re_path('^(?P<question_id>[0-9]+)/clear_notifications/$', views.clear_notification, name='clear_notification'),
    re_path('^(?P<question_id>[0-9]+)/$', views.detail, name='detail'),
    re_path('^(?P<question_id>[0-9]+)/answer/$', views.PostAnswerView.as_view(), name='answer'),
    re_path('^(?P<question_id>[0-9]+)/answer/(?P<ans_id>[0-9]+)/comment$', views.post_comment, name='comment'),
    re_path('^(?P<question_id>[0-9]+)/answer/(?P<ans_id>[0-9]+)/comment/(?P<comment_id>[0-9]+)/delete$', views.delete_comment, name='delete_comment'),
    re_path('^(?P<pk>[0-9]+)/edit/$', views.QuestionUpdate.as_view(), name='edit_question'),
    re_path('^(?P<pk>[0-9]+)/delete/$', views.QuestionDelete.as_view(), name='delete_question'),
    re_path('^(?P<question_id>[0-9]+)/answer/(?P<pk>[0-9]+)/edit$', views.AnswerUpdate.as_view(), name='edit_answer'),
    re_path('^(?P<question_id>[0-9]+)/answer/(?P<pk>[0-9]+)/delete$', views.AnswerDelete.as_view(), name='delete_answer'),
    re_path('^vote/(?P<text_type>[a-z]+)/(?P<text_id>[0-9]+)/change=(?P<score_change>[+-]1)/$', views.vote, name='vote'),
]

pso/homepage/forms.py
from django.contrib.auth.models import User
from django import forms
from questionpage.models import Question

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'password']

pso/homepage/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout as django_logout, get_user
from django.views.generic import View, ListView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Q
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from questionpage.models import Question, Notification, Answer
from .forms import UserForm
from functools import reduce
import json
import operator


def home(request):
    paginator = Paginator(Question.objects.all(), per_page=10)
    page_num = request.GET.get('page')
    if page_num is None:
        page_num = '1'
    questions = paginator.get_page(page_num)
    recent_question_pairs = []
    top_question_pairs = []
    alpha_question_pairs = []
    offset = int(page_num) - 1
    for q in Question.objects.all().order_by('date_posted')[offset:10]:
        length = len(Answer.objects.filter(question_answered=q.id))
        recent_question_pairs.append((q, length))
    for q in Question.objects.all().order_by('title')[:10]:
        length = len(Answer.objects.filter(question_answered=q.id))
        alpha_question_pairs.append((q, length))
    for q in Question.objects.all().order_by('score'):
        top_question_pairs.append((q, q.score))
    user = get_user(request)
    context = {
        'user': user,
        'all_questions': questions,
        'recent_questions': recent_question_pairs,
        'top_questions': top_question_pairs,
        'alpha_questions': alpha_question_pairs,
        'all_notifications': [],
    }
    if not user.is_anonymous:
        notifications = Notification.objects.filter(user=get_user(request))
        context['all_notifications'] = notifications
    return render(request, 'homepage/home.html', context)


def logout(request):
    django_logout(request)
    return redirect('/')


def faq(request):
    context = {'user': request.user }
    return render(request, 'homepage/faq.html', context)


def contactus(request):
    context = {'user': request.user }
    return render(request, 'homepage/contactus.html', context)


class UserFormView(View):
    form_class = UserForm
    template_name = 'homepage/registration_form.html'

    def get (self, request):
        form = self.form_class(None)
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        form = self.form_class(request.POST)

        if form.is_valid():
            user = form.save(commit=False)
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user.set_password(password)
            user.save()

            user = authenticate(username=username, password=password)

            if user is not None and user.is_active:
                login(request, user)
                return redirect('/')
        return render(request, self.template_name, {'form': form})


class LoginFormView(View):
    form_class = UserForm
    template_name = 'homepage/login_form.html'

    def get (self, request):
        form = self.form_class(None)
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)

        if user is not None and user.is_active:
            login(request, user)
            return redirect('/')

        form = self.form_class(request.POST)
        return render(request, self.template_name, {'form': form})


class SearchListView(ListView):
    template_name = 'homepage/home.html'
    context_object_name = 'recent_questions'

    def get_queryset(self):
        query = self.request.GET.get('query')
        if query is not None:
            q_pairs = []
            if "[" in query and "]" in query:
                for q in self.get_tag_queryset(query):
                    q_pairs.append((q, len(Answer.objects.filter(question_answered=q.id))))
                return q_pairs
            else:
                for q in self.get_search_queryset(query):
                    q_pairs.append((q, len(Answer.objects.filter(question_answered=q.id))))
                return q_pairs

    def get_search_queryset(self, query):
        qs = query.split() or ['']
        mask1 = reduce(operator.and_, (Q(title__icontains=q) for q in qs))
        mask2 = reduce(operator.and_, (Q(body__icontains=q) for q in qs))
        return Question.objects.filter(mask1 | mask2)

    def get_tag_queryset(self, query):
        tags = query.split() or ['']
        tags = [tag[1:-1] for tag in tags if self.is_valid_tag(tag)]
        if not tags: return []
        mask = reduce(operator.and_, (Q(tags__icontains=tag) for tag in tags))
        return Question.objects.filter(mask)

    def is_valid_tag(self, tag):
        if len(tag) <3 or tag[0] != "[" or tag[-1] != "]": return False
        else: return tag[1:-1].isalnum()


def autocomplete(request):
    if request.is_ajax():
        query = request.GET.get('term', '')
        questions = Question.objects.filter(title__icontains=query)[:20]
        results = []
        for q in questions:
            results.append({'id': q.pk, 'label': q.title, 'value': q.title})
        data = json.dumps(results)
    else:
        data = 'fail'

    mimetype = 'application/json'
    return HttpResponse(data, mimetype)

pso/homepage/templates/homepage/contactus.html
<!-- HTML code for Contact Us page -->

{% extends 'base.html' %}
{% load static %}

{% block title %}PSO - Contact Us{% endblock %}

{% block extra_head %}
<link href="{% static 'css/navbar.css' %}" type='text/css' rel='stylesheet' />
<link href="{% static 'homepage/css/contactus.css' %}" type='text/css' rel='stylesheet' />
{% endblock %}

{% block content %}
<!-- top navigation bar -->
{% include 'navbar.html' %}

<!-- informational panel -->
<div class="row">
    <div class="col-md-6 contact_info">
        <h1 class="display-4">Contact Penn Stack Overflow</h1>
        <hr class="section_header">
        <br>
        <p><b>Need help with navigating or using the site?</b><br>
            Check out our <a href="{% url 'homepage:faq' %}">FAQ</a> page to see if you can find your answer there.
            <br><br>
            <b>Want to share feedback about our products?</b><br>
            Feel free to contact us with a message about your suggestions for the site.<br>
            We are always looking to improve the experience for users like you.
            <br><br>
            <b>What's in a great support request?</b><br>
            Provide us with as much essential information as possible.<br>
            Include any links that are related to your problem.
        </p>
    </div>
    <div class="col-md-4 center">
        <br><br>
        <center>
            <img class="img-responsive contact_image" src="{% static 'contact_image.jpg' %}">
        </center>
    </div>
</div>
<br><br>

<!-- message form -->
<div class="col-md-8 contact_form">
    <form action="#" method="post">
        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    <label for="form_name">Firstname *</label>
                    <input type="text" name="firstname" class="form-control" placeholder="Please enter your firstname" required="required" data-error="Firstname is required.">
                    <div class="help-block with-errors"></div>
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <label for="form_lastname">Lastname *</label>
                    <input type="text" name="lastname" class="form-control" placeholder="Please enter your lastname" required="required" data-error="Lastname is required.">
                    <div class="help-block with-errors"></div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    <label for="form_email">Email *</label>
                    <input type="email" name="email" class="form-control" placeholder="Please enter your email" required="required" data-error="Valid email is required.">
                    <div class="help-block with-errors"></div>
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <label for="form_phone">Phone</label>
                    <input type="tel" name="phone" class="form-control" placeholder="Please enter your phone">
                    <div class="help-block with-errors"></div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="form-group">
                    <label for="form_message">Message *</label>
                    <textarea name="message" class="form-control" placeholder="Message for me" rows="4" required="required" data-error="Please,leave us a message."></textarea>
                    <div class="help-block with-errors"></div>
                </div>
            </div>
            <div class="col-md-12" action="">
                {% csrf_token %}
                <input type="submit" class="btn btn-success btn-send" value="Send message">
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <p class="text-muted"><strong>*</strong> These fields are required.</p>
            </div>
        </div>
    </form>
</div>

{% endblock %}

pso/homepage/templates/homepage/display_alphabetical_question.html
<!-- template code for displaying list of alphabetically sorted questions -->

{% for question, num in alpha_questions %}
<div class="row">
    <div class="col-sm-2 num_answers">
        <h4>{{ num }}</h4><h6>Answers</h6>
    </div>
    <div class="col-sm-10">
        <a href="/questions/{{ question.id }}/"><h4>{{ question.title }}</h4></a>
        <p> Asked by <a href="/profile/{{question.author}}">{{ question.author }}</a> on {{ question.date_posted }} </p>
    </div>
</div>
<hr class="divider"/>
{% endfor %}

pso/homepage/templates/homepage/display_hot_question.html
<!-- template code for displaying list of top voted within past 24 hours questions -->

{% load homepage_custom_tags %}

{% for question, num in recent_questions %}
    {% if question.date_posted|test_if_recent %}
        <div class="row">
            <div class="col-sm-2 num_answers">
                <h4>{{ num }}</h4><h6>Answers</h6>
            </div>
            <div class="col-sm-10">
                <a href="/questions/{{ question.id }}/"><h4>{{ question.title }}</h4></a>
                <p> Asked by <a href="/profile/{{question.author}}">{{ question.author }}</a> on {{ question.date_posted }} </p>
                <p>Will be displayed until: {{ question.date_posted|add_24_hours }}</p>
            </div>
        </div>
        <hr class="divider">
    {% endif %}
{% endfor %}

pso/homepage/templates/homepage/display_recent_question.html
<!-- template code for displaying list of questions -->

{% for question, num in recent_questions reversed %}
<div class="row">
    <div class="col-sm-2 num_answers">
        <h4>{{ num }}</h4><h6>Answers</h6>
    </div>
    <div class="col-sm-10">
        <a href="/questions/{{ question.id }}/"><h4>{{ question.title}}</h4></a>
        <p> Asked by <a href="/profile/{{question.author}}"> {{question.author}}</a> on {{ question.date_posted }} </p>
    </div>
</div>
<hr class="divider"/>
{% endfor %}

pso/homepage/templates/homepage/display_top_question.html
<!-- template code for displaying list of top voted questions -->

{% for question, num in top_questions reversed %}
<div class="row">
    <div class="col-sm-2 num_answers">
        <h4>{{ num }}</h4><h6>Votes</h6>
    </div>
    <div class="col-sm-10">
        <a href="/questions/{{ question.id }}/"><h4>{{ question.title }}</h4></a>
        <p> Asked by <a href="/profile/{{question.author}}">{{ question.author }}</a> on {{ question.date_posted }} </p>
    </div>
</div>
<hr class="divider"/>
{% endfor %}

pso/homepage/templates/homepage/home.html
<!-- HTML code for displaying home page -->

{% extends 'base.html' %}
{% load static %}

{% block title %}Welcome to PSO{% endblock %}

{% block extra_head %}
<link href="{% static 'css/navbar.css' %}" rel="stylesheet" type="text/css"/>
<link href="{% static 'homepage/css/home.css' %}" rel="stylesheet" type="text/css"/>
<link href="https://fonts.googleapis.com/css?family=Roboto:400" rel="stylesheet">
{% endblock %}

{% block content %}

<!-- top navigation bar -->
{% include 'navbar.html' %}

<!-- homepage jumbotron -->
{% if user.is_anonymous %}
<div class="jumbotron">
    <div class="row">
        <div class="col-xs-6 jumbo-left">
            <h2 class="display-4">Learn, Share, Build</h2>
            <p class="lead">
              Each month, thousands of students come to Penn Stack Overflow
              to learn, share their knowledge, and build their careers.
            </p>
            <p>Come join Penn's largest developer community.</p>
        </div>

        <div class="col-xs-6 jumbo-right">
            <form action="/register/" method="post">
                {% csrf_token %}
                <div class="row">
                    <!-- username box -->
                    <div class="form-group">
                        <div class="col-md-8">
                            <label>Username</label>
                            <input type="username" name="username" class="form-control" placeholder="Enter username">
                        </div>
                    </div>
                </div><br>

                <div class="row">
                    <!-- password box -->
                    <div class="col-md-8">
                        <div class="form-group">
                            <label>Password</label>
                            <input type="password" name="password" class="form-control" placeholder="Password">
                        </div>
                    </div>
                </div>
                <button type="submit" class="btn btn-default">Sign Up</button><br>
                <small style="color:white;" class="form-text text-muted">
                    By registering, you agree to the private policy and terms of service.
                </small>
            </form>
        </div>
    </div>
</div>

{% else %}


{% endif %}

<!-- homepage dynamic tabs -->
<div class="row">
    <div class="col-md-8">
        <div class="right-tabs clearfix">
            <ul class="nav nav-tabs">
                <li class="active"><a href="#tab_a" data-toggle="tab">Home</a></li>
                <li><a href="#tab_b" data-toggle="tab">Top</a></li>
                <li><a href="#tab_c" data-toggle="tab">Alphabetical</a></li>
                <li><a href="#tab_d" data-toggle="tab">Hot</a></li>
            </ul>
            <div class="tab-content">

                <div class="tab-pane in active" id="tab_a">
                    <div class="panel panel-default" id="question-panel">
                        <div class="panel-heading">
                            <h2>Recent Questions on Penn Stack Overflow</h2>
                        </div>
                        <div class="panel-body">
                            {% include "homepage/display_recent_question.html" %}
                        </div>
                    </div>
                </div>

                <div class="tab-pane" id="tab_b">
                    <div class="panel panel-default" id="question-panel">
                        <div class="panel-heading">
                            <h2>Top Questions on Penn Stack Overflow</h2>
                        </div>
                        <div class="panel-body">
                            {% include "homepage/display_top_question.html" %}
                        </div>
                    </div>
                </div>

                <div class="tab-pane" id="tab_c">
                    <div class="panel panel-default" id="question-panel">
                        <div class="panel-heading">
                            <h2>Questions on Penn Stack Overflow by Title</h2>
                        </div>
                        <div class="panel-body">
                            {% include "homepage/display_alphabetical_question.html" %}
                        </div>
                    </div>
                </div>

                <div class="tab-pane" id="tab_d">
                    <div class="panel panel-default" id="question-panel">
                        <div class="panel-heading">
                            <h2>Hot Questions on Penn Stack Overflow</h2>
                        </div>
                        <div class="panel-body">
                            {% include "homepage/display_hot_question.html" %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <!-- search button -->
        <div class="ui-widget">
            <form class="formgroup" action="{% url 'homepage:search' %}" method="get">
                <input class="searchfield" id="searchbox" name="query" type="text" placeholder="Search">
                <button style="font-family:'Roboto', sans-serif;" class="searchbutton" type="submit">Submit</button>
            </form>
        </div>

        <!-- script for autocomplete when searching for questions -->
        <script src={% static 'homepage/js/autocomplete.js' %} type="text/javascript"></script>

        <!-- informational panel -->
        <div class="panel panel-default" id="info-panel">
            <div class="panel-body">
                <h3> Notifications </h3><hr />
                <div class="blocktext">
                    <ul>
                        {% if not all_notifications %}
                        <p> You have no notifications, but don't worry!
                        {% endif %}
                        {% for notification in all_notifications %}
                        <li> <a href="{% url 'questionpage:clear_notification' notification.question.id %}"> {{ notification }} </a>
                        {% endfor %}
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>

{% include 'pagination.html' %}
{% endblock %}

pso/homepage/templates/homepage/login_form.html
<!-- HTML code for logging into user account -->

{% extends 'base.html' %}
{% load static %}

{% block title %}PSO - Login{% endblock %}

{% block extra_head %}
<link href="{% static 'css/navbar.css' %}" rel="stylesheet" type="text/css"/>
<style>
    body {
        margin-top: 75px;
        background-color: #F0F2EF;
    }

    .account-data {
        margin-left: 80px;
    }
</style>
{% endblock %}

{% block content %}
<!-- top navigation bar -->
{% include 'navbar.html' %}

<div class="row">
    <div class="col-md-4 account-data">
        <h2> Login to your account </h2><br>
        <form class="form-horizontal" role="form" action="" method="post">
            {% csrf_token %}
            {% include 'form_template.html' %}
            <div class="form-group">
                <div class="col-sm-offset-2 col-sm-10">
                    <button type="submit" class="btn btn-success">Submit</button>
                </div>
            </div>
        </form>
    </div>
</div>

{% endblock %}

pso/homepage/templates/homepage/registration_form.html
<!-- HTML code for registering a new account -->

{% extends 'base.html' %}
{% load static %}

{% block title %}PSO - Register{% endblock %}

{% block extra_head %}
<link href="{% static 'css/navbar.css' %}" rel="stylesheet" type="text/css"/>
<style>
    body {
        background-color: #F0F2EF;
        margin-top: 75px;
    }

    .account-data {
        margin-left: 80px;
    }
</style>
{% endblock %}

{% block content %}
<!-- top navigation bar -->
{% include 'navbar.html' %}

<div class="row">
    <div class="col-md-4 account-data">
        <h2> Create New Account </h2><br>
        <form class="form-horizontal" role="form" action="" method="post">
            {% csrf_token %}
            {% include 'form_template.html' %}
            <div class="form-group">
                <div class="col-sm-offset-2 col-sm-10">
                    <button type="submit" class="btn btn-success">Submit</button>
                </div>
            </div>
        </form>
    </div>
</div>

{% endblock %}

pso/homepage/templates/homepage/searchresults.html
<h1>Search results are </h1>